name: Development Pipeline

on:
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Add your linting steps here

  build:
    name: Build and Unit Test
    runs-on: ubuntu-latest

    needs: lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Add your Build steps here

  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Add your deployment steps here

  test-automation:
    name: Test Automation
    runs-on: ubuntu-latest

    needs: deploy

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Add your test automation steps here

  static-analysis:
    name: Static Analysis
    runs-on: ubuntu-latest

    needs: deploy

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Add your static analysis steps here

  security-tooling:
    name: Security Tooling
    runs-on: ubuntu-latest

    needs: deploy

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Add your security tooling steps here
